### ISSUE TITLE
[Critical Bug] When searching for a second time, the results are from first search

### ISSUE THREAD

**Issue by w3ichen** [ScottyLabs/cmucourses#165]
### Expected Behavior

When clicking enter to search again, the page should refresh with the results for the new search

### Steps to Reproduce

1. Search for one class, and hit enter
2. Search for another click and hit enter
3. Results are still from first search

### Device Information

Desktop/Mobile: Desktop
OS: macOS Monterey 12.3.1
Browser Version: Safari 15.4

**Comment by Xavilien** [comment]
Could you provide a screen recording

**Comment by w3ichen** [comment]
Actually, never mind I can't seem to reproduce it anymore. The other day I had to refresh the page for it to show the new results. Maybe I was being too impatient for it to load. Anyways, closing the issue - thanks1

**Comment by w3ichen** [comment]
I take that back, the issue definitely does exist, but hard to reproduce. 
My guess is the bug occurs either if you have the tab open for a while and go to work on other tabs or maybe multiple tabs open.

In the video, you can see it shows the old results even when i hit enter on the search bar!
I think you might be storing cookies on the browser and it's picking up on the old saved search query?


https://github.com/user-attachments/assets/a05110c6-0125-4e2e-a97d-a9c49413af82


https://github.com/user-attachments/assets/0a74da63-3eb4-4025-a4f3-b79ee1323567

**Comment by w3ichen** [comment]
@Xavilien

**Comment by w3ichen** [comment]
Another bug I'm seeing is that the number of stars is always showing as 5 stars even though the number is not 5
![image](https://github.com/user-attachments/assets/fe7ccfc9-8d6d-4d35-bd78-a0e287a22239)

**Comment by Xavilien** [comment]
Yep I think @HeidiTao is working on that. But also, would you be interested in contributing to CMU Courses?

**Comment by w3ichen** [comment]
I wish I could but I have too many other commitments. But really great work with cmucourses, it's an awesome website!

**Comment by Xavilien** [comment]
Hi @w3ichen, I found the source of the bug, turns out the JWT we use to query the data expires after 1 minute and we were not refreshing the token before making backend calls. My latest PR #182 that migrated us to tanstack should have resolved this issue. Thanks for pointing it out!

**Comment by w3ichen** [comment]
Sweet! Thanks so much @Xavilien! 🎉
