### ISSUE TITLE
[Feature] Prerequisite (and Postrequisite) Tree

### ISSUE THREAD

**Issue by btwj** [ScottyLabs/cmucourses#53]
### Description

In the course detail page, render a prerequisite tree. For example, for a course E with prerequisites (A or B) and (C or D), we should show something like

```
A --|
   one of --|
B --|       |
          all of --- E
C --|       |
   one of --|
D --| 
```
Clicking one of the prerequisite courses should in turn render that course's prerequisite tree.

**Comment by Lhwhatever** [comment]
To be done after migration to Prisma: #100

**Comment by aattiyah** [comment]
Hello, can you assign me to the issue?
